İmport

In [1]:
import numpy as np

The Basics

In [2]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a, b, a * b) # allows more options

[1 2 3] [2 3 4] [ 2  6 12]


In [3]:
c = np.array([[9.8, 7.3, 4.1],[6.0, 0.9, 8.3]]) #diffrent row []
c

array([[9.8, 7.3, 4.1],
       [6. , 0.9, 8.3]])

In [4]:
# Get dimension
a.ndim

1

In [5]:
# Get shape
c.shape

(2, 3)

In [6]:
# Get type
# a = np.array([1,2,3], dtype ='int16') # change type
a.dtype

dtype('int32')

In [7]:
# Get size
a.itemsize

4

In [8]:
# Get total size
a.nbytes #a.size * a.itemsize

12

Accessing / Changing specific elements, rows, columns etc

In [9]:
a = np.array(([1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]))
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
print (a[1, 5])
print (a[1, -2]) #can be negatif ones

13
13


In [11]:
print(a[0])
print(a[0, :]) #same

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [12]:
a[:, 2] # ! a[ , 2] nope

array([ 3, 10])

In [13]:
a[0, 1: 6: 2] # [startindex:endindex:stepsize]

array([2, 4, 6])

In [14]:
a[1][5] = -5
a[1][5]

-5

In [15]:
a[:, 2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, -5, 14]])


3-d

In [16]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b, "\n")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 




Basic index // can initialize same way

In [17]:
print(b[1], "\n")
print(b[0][1], "\n")
print(b[1][0][0], "\n")

[[5 6]
 [7 8]] 

[3 4] 

5 



In [18]:
print(b[1, 0, 0], "\n")
print(b[:, 1, :], "\n")
print(b[:, 0, 0], "\n")

5 

[[3 4]
 [7 8]] 

[1 5] 



In [19]:
b[:, 1, :] = [[9, 9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initialize different types of arrays

In [20]:
# ALl 0s matrix
a = np.zeros(5, dtype = int)
print(a , "\n")
a = np.zeros((2, 3)) # make shape 
print(a , "\n")
a = np.zeros((2, 3, 2, 4), dtype = int)
print(a , "\n")

[0 0 0 0 0] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]] 



In [21]:
# All 1s matrix:
a = np.ones(5, dtype = int) # similar .zeros
a #  dtype ='int32' ????

array([1, 1, 1, 1, 1])

In [22]:
a = np.full((2, 2), 99, dtype = 'float32')
a

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [23]:
np.full_like(a, 4, dtype = int)

array([[4, 4],
       [4, 4]])

Random

In [24]:
np.random.rand(4, 2)

array([[0.60822474, 0.01901699],
       [0.21340553, 0.57776137],
       [0.5367009 , 0.8138741 ],
       [0.4729912 , 0.36380992]])

In [25]:
np.random.random_sample(a.shape)

array([[0.74458262, 0.61928984],
       [0.15678427, 0.43484501]])

In [26]:
np.random.randint(7, size= (3, 3)) # int 

array([[0, 5, 5],
       [6, 0, 1],
       [2, 1, 1]])

In [27]:
np.identity(5, dtype = int) # identiy matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])