https://numpy.org/doc/stable/contents.html

İmport

In [1]:
import numpy as np

The Basics

In [2]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a, b, a * b)  # allows more options

[1 2 3] [2 3 4] [ 2  6 12]


In [3]:
c = np.array([[9.8, 7.3, 4.1], [6.0, 0.9, 8.3]])  # diffrent row []
c

array([[9.8, 7.3, 4.1],
       [6. , 0.9, 8.3]])

In [4]:
# Get dimension
a.ndim

1

In [5]:
# Get shape
c.shape

(2, 3)

In [6]:
# Get type
# a = np.array([1,2,3], dtype ='int16') # change type
a.dtype

dtype('int32')

In [7]:
# Get size
a.itemsize

4

In [8]:
# Get total size
a.nbytes  # a.size * a.itemsize

12

Accessing / Changing specific elements, rows, columns etc

In [9]:
a = np.array(([1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]))
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
print(a[1, 5])
print(a[1, -2])  # can be negatif ones

13
13


In [11]:
print(a[0])
print(a[0, :])  # same

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [12]:
a[:, 2]  # ! a[ , 2] nope

array([ 3, 10])

In [13]:
a[0, 1: 6: 2]  # [startindex:endindex:stepsize]

array([2, 4, 6])

In [14]:
a[1][5] = -5
a[1][5]

-5

In [15]:
a[:, 2] = [1, 2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, -5, 14]])


3-d

In [16]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b, "\n")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 




Basic index // can initialize same way

In [17]:
print(b[1], "\n")
print(b[0][1], "\n")
print(b[1][0][0], "\n")

[[5 6]
 [7 8]] 

[3 4] 

5 



In [18]:
print(b[1, 0, 0], "\n")
print(b[:, 1, :], "\n")
print(b[:, 0, 0], "\n")

5 

[[3 4]
 [7 8]] 

[1 5] 



In [19]:
b[:, 1, :] = [[9, 9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initialize different types of arrays

In [20]:
# ALl 0s matrix
a = np.zeros(5, dtype=int)
print(a, "\n")
a = np.zeros((2, 3))  # make shape
print(a, "\n")
a = np.zeros((2, 3, 2, 4), dtype=int)
print(a, "\n")

[0 0 0 0 0] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]] 



In [21]:
# All 1s matrix:
a = np.ones(5, dtype=int)  # similar .zeros
a  # dtype ='int32' ????

array([1, 1, 1, 1, 1])

In [22]:
a = np.full((2, 2), 99, dtype='float32')
a

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [23]:
np.full_like(a, 4, dtype=int)

array([[4, 4],
       [4, 4]])

Random

In [24]:
np.random.rand(4, 2)

array([[0.27617793, 0.24083907],
       [0.13024343, 0.29554033],
       [0.65222256, 0.26491269],
       [0.49236145, 0.64088913]])

In [25]:
np.random.random_sample(a.shape)

array([[0.2822069 , 0.6978692 ],
       [0.99884654, 0.0364466 ]])

In [26]:
np.random.randint(7, size=(3, 3))  # int

array([[3, 5, 5],
       [1, 5, 4],
       [1, 6, 0]])

In [27]:
np.identity(5, dtype=int)  # identiy matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [29]:
output = np.ones((5, 5), dtype=int)
print(output, "\n")

z = np.zeros((3, 3), dtype=int)
print(z, "\n")

output[1: 4, 1: 4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


!!!!!!! copying array --> .copy() 
else --> changing one affect another

In [30]:
a = np.array([1, 5, 9])
print(a, " a")
b = a
print(b, " b")
a[0] = 55
print(a, " a")
print(b, " b")

[1 5 9]  a
[1 5 9]  b
[55  5  9]  a
[55  5  9]  b


In [31]:
b = a.copy()
b[0] = -3
print(a, " a")
print(b, " b")

[55  5  9]  a
[-3  5  9]  b


Math

https://numpy.org/doc/stable/reference/routines.math.html

In [32]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a + 2)  # add each element

a + 2  # assign edilmediği için etki etmez
print(a)

[1 2 3 4 5]
[3 4 5 6 7]
[1 2 3 4 5]


In [33]:
print(a * 2)

[ 2  4  6  8 10]


In [34]:
a *= 2
a

array([ 2,  4,  6,  8, 10])

In [35]:
b = np.array([2, 2, 1, 1, 7])
a + b

array([ 4,  6,  7,  9, 17])

In [36]:
b ** 2

array([ 4,  4,  1,  1, 49], dtype=int32)

In [37]:
# Take the sin
print(np.cos(a))
print(np.tan(a))

[-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153]
[-2.18503986  1.15782128 -0.29100619 -6.79971146  0.64836083]


Linear 

https://numpy.org/doc/stable/reference/routines.linalg.html

In [38]:
a = np.ones((2, 3), dtype=int)
print(a, "\n")

b = np.full((3, 2), 5)
print(b, "\n")

np.matmul(a, b)

[[1 1 1]
 [1 1 1]] 

[[5 5]
 [5 5]
 [5 5]] 



array([[15, 15],
       [15, 15]])

In [39]:
# determinant

c = np.identity(4)
print(c)
np.linalg.det(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


1.0

Statistics 
 
https://numpy.org/doc/stable/reference/routines.statistics.html?highlight=statistics

In [40]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
print(np.min(c))
print(np.max(c))
print(np.max(c, axis=1))

1
6
[3 6]


In [42]:
print(np.sum(c))

21


Reorganize

In [43]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before, " \n")

after = before.reshape((4, 2))  # Must be equal * // 2, 2, 2
print(after)

[[1 2 3 4]
 [5 6 7 8]]  

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
# Vertically stacking vectors

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [45]:
# Horizontal stack

h1 = np.ones((2, 4), dtype=int)
h2 = np.zeros((2, 2), dtype=int)

np.hstack([h1, h2])

array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]])

Miscellaneous

load data from file


In [46]:
filedata = np.genfromtxt("test.txt", delimiter=',')  # delimater --> part
filedata

array([[1., 5., 6., 7., 2., 8., 9., 1.],
       [4., 5., 7., 9., 3., 1., 2., 4.],
       [9., 7., 6., 1., 3., 7., 5., 6.]])

In [47]:
filedata.astype(int)  # or , dtype = int # or 'int32'
### filedata = filedata.astype(int)

array([[1, 5, 6, 7, 2, 8, 9, 1],
       [4, 5, 7, 9, 3, 1, 2, 4],
       [9, 7, 6, 1, 3, 7, 5, 6]])

Boolean Masking and advanced indexing 

In [48]:
filedata > 5

array([[False, False,  True,  True, False,  True,  True, False],
       [False, False,  True,  True, False, False, False, False],
       [ True,  True,  True, False, False,  True, False,  True]])

In [49]:
filedata[filedata > 5]  # indexes which ones bigger than 5

array([6., 7., 8., 9., 7., 9., 9., 7., 6., 7., 6.])

In [50]:
# can index with a list in NumPY ???
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [51]:
np.any(filedata > 5, axis=0)  # look vertical is any one bigger than 5

array([ True,  True,  True,  True, False,  True,  True,  True])

In [52]:
(np.all(filedata > 5, axis=0))  # look all

array([False, False,  True, False, False, False, False, False])

In [53]:
## ~ reverse
x = np.any(filedata < 5, axis=0)
y = ~np.any(filedata < 5, axis=0)
print(x)
print(y)

[ True False False  True  True  True  True  True]
[False  True  True False False False False False]


In [54]:
for i in range(30):
    a = np.array([i])

a

array([29])

In [55]:
a = np.empty(shape=(30), dtype=int)
for i in range(30):
    a[i] = i + 1

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
a = np.empty(shape=(5, 6), dtype=int)
a

for i in range(len(a)):
    a[i] = i+1
print(a)
len(a)

[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]
 [5 5 5 5 5 5]]


5

In [72]:
a = np.empty(shape=(5, 6), dtype=int)

for i in range(a.shape[0]):
    for k in range(a.shape[1]):
        a[i][k] = i * a.shape[1] + k

a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [73]:
a = np.arange(0, 30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [74]:
a[2:4, 0:2]

array([[12, 13],
       [18, 19]])

In [75]:
a[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 1,  8, 15, 22])

In [79]:
a[[0, 2, 3], 3:]

array([[ 3,  4,  5],
       [15, 16, 17],
       [21, 22, 23]])